language: go

sudo: false

go:
  - "1.12"

env:
  - GO111MODULE=on

before_script:
  - go mod download
  - go get -u github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci