language: go

sudo: false

go:
  - "1.11"

env:
  - GO111MODULE=on

before_script:
  - go mod vendor
  - go install -mod vendor github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci